on: [push]

name: CI

jobs:
  build_and_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install cargo-insta
      - run: cargo insta test --accept
        env:
            RUST_BACKTRACE: 1
